
defaults:
  - global
  - nbody: 1gpch
  - fit: quijote_HR
  - bias: cic_hod
  - survey: cmass_ngc
  # - filter: random  # not default
  - diag: default
  - _self_

# What base sim to use
sim: pmwd

# whether to run on multiple snapshots and use lightcone snapshot extrapolation
# (if available)
multisnapshot: True
